import LanguageProvider from '@/i18n/LanguageProvider';
import { availableLanguageTags, languageTag } from '@/i18n/generated/runtime';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<LanguageProvider>
			<html lang={languageTag()}>
				<body>
					<nav>
						{availableLanguageTags.map((tag) => (
							<a href={tag} key={tag}>
								{tag}
							</a>
						))}
					</nav>
					{children}
				</body>
			</html>
		</LanguageProvider>
	);
}
