export const LANG_COLUMN_NAME = 'lang';
export type LangColumnName = typeof LANG_COLUMN_NAME;

export const USER_ID_LENGTH = 15;
export const EMAIL_CONFIRMATION_CODE_LENGTH = 6;

export const LABELING_SURVEY_TITLE_MAX = 250;
export const LABELING_SURVEY_SUMMARY_MAX = 1500;
export const LABELING_SURVEY_DESCRIPTION_MAX = 5000;
export const LABELING_SURVEY_SLIDER_STEP_COUNT_MAX = 10;

export const IMAGE_POOL_TITLE_MAX = 150;
export const IMAGE_POOL_DESCRIPTION_MAX = 2500;
